name: docker push
on:
  create:
  push:
    branches:
      - main

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: docker-publish
        if: github.event.ref_type == 'tag'
        uses: docker://docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        with:
          entrypoint: sh
          args: ci/docker-build.sh
