name: Test Dockerfile
on:
  pull_request:
    branches:
      - main

jobs:
  test-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: fsouza/docker-publish-action@main
        with:
          docker-image: fsouza/docker-ssl-proxy
          skip-push: true
