name: Test Dockerfile
on:
  pull_request:
    branches:
      - master

jobs:
  test-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: test Dockerfile
        uses: docker://docker
        with:
          entrypoint: docker
          args: build .
